MyAcadmy/Models/cour.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAcadmy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cour()
        {
            this.data_of_student = new HashSet<data_of_student>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int teacher { get; set; }
        public System.DateTime datestart { get; set; }
        public string imag { get; set; }
        public int dep { get; set; }
        public string contentcourse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<data_of_student> data_of_student { get; set; }
        public virtual Department Department { get; set; }
        public virtual trainer trainer { get; set; }
    }
}

MyAcadmy/Controllers/coursController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.Interception;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Web.UI.WebControls;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using MyAcadmy.Models;

namespace courses.Controllers
{
    public class coursController : Controller
    {
        private courseEntities db = new courseEntities();

        // GET: cours
        [Authorize(Roles ="HR")]
        public ActionResult Index()
        {
            var cours = db.cours.Include(c => c.Department).Include(c => c.trainer);
            return View(cours.ToList());
        }

        public ActionResult sh(string shr)
        {
            var kariem = db.cours.Where(s => s.name.Contains(shr)).ToList();
            return View( kariem);
        }

        public ActionResult Searching( string search)
        {
            var courses = db.cours.Where(s => s.name.Contains(search)).ToList();
            ViewBag.ss = "ss";
            return View("Index",courses);
        }
        // GET: cours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cour cour = db.cours.Find(id);
            Session["id"] = id;
            if (cour == null)
            {
                return HttpNotFound();
            }
            return View(cour);
        }

        // GET: cours/Create
        public ActionResult Create()
        {
            ViewBag.dep = new SelectList(db.Departments, "id", "name");
            ViewBag.teacher = new SelectList(db.trainers, "id", "name");
            return View();
        }

        // POST: cours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,teacher,datestart,imag,dep")] cour cour, HttpPostedFileBase file , DateTime date)
        {
            string filename = Path.GetFileName(file.FileName);
            string _filename = DateTime.Now.ToString("yymmssfff") + filename;
            string exe = Path.GetExtension(file.FileName);
            string path = Path.Combine(Server.MapPath("~/Content/images/"), _filename);
            cour.imag = "~/Content/images/" + _filename;
            try
            {
                if (exe.ToLower() == ".png" || exe.ToLower() == ".jpg" || exe.ToLower() == ".jpeg" || exe.ToLower() == "jfif" || exe.ToLower() == "gif")
                {
                    if (file.ContentLength < 1000000)
                    {
                        cour.datestart = date;
                        db.cours.Add(cour);
                        if (db.SaveChanges() > 0)
                            file.SaveAs(path);
                        return RedirectToAction("Index");

                    }

                }
                else
                {
                    ViewBag.ss = "kkkkkkk";
                    return PartialView("Error", ViewBag.ss);
                }
            }

            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "EmployeeInfo", "Create"));
            }

            
            ViewBag.dep = new SelectList(db.Departments, "id", "name", cour.dep);
            ViewBag.teacher = new SelectList(db.trainers, "id", "name", cour.teacher);
            return View(cour);
        }

        // GET: cours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cour cour = db.cours.Find(id);
            if (cour == null)
            {
                return HttpNotFound();
            }
            ViewBag.dep = new SelectList(db.Departments, "id", "name", cour.dep);
            ViewBag.teacher = new SelectList(db.trainers, "id", "name", cour.teacher);
            return View(cour);
        }

        // POST: cours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,teacher,datestart,imag,dep")] cour cour , HttpPostedFileBase file ,DateTime date)
        {
                string name = Path.GetFileName(file.FileName);
                string _name = DateTime.Now.ToString("yymmssfff") + name;
                string exe = Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("~/Content/images/"), _name);
                cour.imag = "~/Content/images/" + _name;
                if (exe.ToLower() == ".png" || exe.ToLower() == ".jpg" || exe.ToLower() == ".jpeg" || exe.ToLower() == ".jfif" || exe.ToLower() == ".gif")
                {
                    if (file.ContentLength < 1000000)
                    {
                        cour.datestart = date;
                        db.Entry(cour).State = EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            file.SaveAs(path);
                            return RedirectToAction("Index");
                        }
                    }   
                }
                ViewBag.ss = "الصورة لم ليس لها سياق خارجي";
                ViewBag.dep = new SelectList(db.Departments, "id", "name", cour.dep);
                ViewBag.teacher = new SelectList(db.trainers, "id", "name", cour.teacher);
                return View(cour);
             
        }

        // GET: cours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cour cour = db.cours.Find(id);
            if (cour == null)
            {
                return HttpNotFound();
            }
            return View(cour);
        }

        // POST: cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cour cour = db.cours.Find(id);
            if (db.data_of_student.Where(s => s.id_courese == id).Count() > 0)
            {
                List<data_of_student> data = db.data_of_student.Where(s => s.id_courese == id).ToList();
                foreach (var item in data)
                {
                    db.data_of_student.Remove(item);
                    db.SaveChanges();
                }
            }
            db.cours.Remove(cour);
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        /* 
          data-of-student
         */
        [HttpGet]
        [Authorize()]
        public ActionResult Apply(int?id)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userid = User.Identity.GetUserId();
                if (db.data_of_student.Where(s => s.id_student == userid && s.id_courese == id).ToList().Count() > 0)
                {
                    ViewBag.oo = "Error";
                    return PartialView("_modal");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Apply(data_of_student data ,string cars, string mil)
        {
            var userid = User.Identity.GetUserId();           
            
                if (ModelState.IsValid)
                {
                    data.id_student = userid;
                    data.id_courese = (int)Session["id"];
                    if (cars == "Select")
                    {
                        ViewBag.ss = "Please select your gender";
                        return View();
                    }
                    else
                    {
                        data.gender = cars;
                    }
                    courseEntities db = new courseEntities();
                var mail = new MailMessage();
                var user_id = User.Identity.GetUserId();
                var currentuser = db.AspNetUsers.Where(s => s.Id == user_id).FirstOrDefault();
                var logininfo = new NetworkCredential("jkhaled497@gmail.com", "KHALEDJAMAL");
                mail.From = new MailAddress("jkhaled497@gmail.com");
                mail.To.Add(new MailAddress(mil));
                mail.Subject = "مرحبا";
                mail.Body = "صديقي";
                SmtpClient stmp = new SmtpClient("smtp.gmail.com", 587);
                stmp.EnableSsl = true;
                stmp.Credentials = logininfo;
                stmp.Send(mail);
                data.gamil = mil;
                db.data_of_student.Add(data);
                    if (db.SaveChanges() > 0)
                    {
                        ViewBag.ss = "Applying for this courses is done";
                        return RedirectToAction("Index", "Home");

                    }
                    else
                    {
                        ViewBag.ss = "Sorry Please write right email";

                    }
                }
            ModelState.Clear();
            return View();
        }
        public ActionResult mycourses() {
            var userid = User.Identity.GetUserId();

MyAcadmy/Views/cours/Apply.cshtml
@model MyAcadmy.Models.data_of_student

@{
    ViewBag.Title = "Apply";
}

<h2>Apply</h2>
<div>
    @if (ViewBag.ss != null)
    {
        <h3 style="color:green;">@ViewBag.ss</h3>
    }
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>data_of_student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="custom-select" style="width:200px;">
                    <select name="cars" class="form-control col-md-6">
                        <option value="Select">Select gender:</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gamil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gamil, "mil", "mil", new { htmlAttributes = new { @class = "form-control" } })
                <span id="span"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telephone, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @if (ViewBag.oo != null)
                {
                    <script>
                        alert("You are selected this courses befor")
                    </script>
                }
            </div>
        </div>
    </div>
    <div>
        @if (ViewBag.oo != null)
        {
            

            <!-- The Modal -->
            <div class="modal fade" id="myModal">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                            <h4 class="modal-title">Modal Heading</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                            Modal body..
                        </div>

                        <!-- Modal footer -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>

        }
    </div>

    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyAcadmy/Views/cours/Create.cshtml
@model MyAcadmy.Models.cour

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","cours",FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>cour</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dep, "dep", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("dep", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.dep, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datestart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="date" id="datetime-local" class="control-label col-md-2" />
                @Html.ValidationMessageFor(model => model.datestart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" />
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.teacher, "teacher", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("teacher", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.teacher, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAcadmy/Views/cours/Delete.cshtml
@model MyAcadmy.Models.cour

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>cour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datestart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datestart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trainer.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trainer.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyAcadmy/Views/cours/Details.cshtml
@model MyAcadmy.Models.cour

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>cour</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Course Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datestart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datestart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imag)
        </dt>

        <dd>
            <img src="@Url.Content(Model.imag)" height="100" width="100" />
        </dd>

        <dt>

        <dt>
            @Html.DisplayName("Doctor : ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trainer.name)
        </dd>
        <dt>
            @Html.DisplayName("Conten Course")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentcourse)
        </dd>

    </dl>
</div>
<p>
   
    <a href="~/cours/Apply/@Model.id">
        Apply for Courses
    </a>

    <!-- The Modal -->


</p>

MyAcadmy/Views/cours/Edit.cshtml
@model MyAcadmy.Models.cour

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<h2>
    @ViewBag.ss
</h2>

@using (Html.BeginForm("Edit" ,"cours" , FormMethod.Post ,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>cour</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.contentcourse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contentcourse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contentcourse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.teacher, "teacher", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("teacher", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.teacher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datestart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="date" name="date" id="date" />
                @Html.ValidationMessageFor(model => model.datestart, "", new { @class = "text-danger" })
            </div>
        </div>
        <p class="alert-info" id="alert"></p>

        <div class="form-group">
            @Html.LabelFor(model => model.imag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" />
                @Html.ValidationMessageFor(model => model.imag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dep, "dep", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("dep", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.dep, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAcadmy/Views/cours/Index.cshtml
@model IEnumerable<MyAcadmy.Models.cour>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Searching", "cours", FormMethod.Post)){
    <b>serch by name of coursese</b><input type="search" name="search" />
    <input type="submit" value="submite" />
    
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datestart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contentcourse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.trainer.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datestart)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contentcourse)
        </td>
        <td>
            <img src="@Url.Content(item.imag)" height="50" width="50" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.trainer.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

MyAcadmy/Views/cours/Searching.cshtml
@model IEnumerable<MyAcadmy.Models.cour>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datestart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contentcourse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.trainer.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datestart)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.imag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contentcourse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.trainer.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

MyAcadmy/Views/cours/message.cshtml
@model كورسات.Models.mesag

@{
    ViewBag.Title = "message";
}

<h2>message</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>mesag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.email,
           htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.@object, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.@object, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.@object, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyAcadmy/Views/cours/unfollow.cshtml
@model MyAcadmy.Models.data_of_student

@{
    ViewBag.Title = "unfollow";
}

<h2>unfollow</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>data_of_student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cour.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cour.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cour.imag)
        </dt>

        <dd>
           <img src="@Url.Content(Model.cour.imag)" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>